# Generated by Django 2.2.3 on 2019-07-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_public_key', models.CharField(max_length=64)),
                ('interface_private_key', models.CharField(max_length=64)),
                ('interface_address', models.CharField(max_length=255)),
                ('server_public_key', models.CharField(max_length=64)),
                ('server_endpoint', models.CharField(max_length=255)),
                ('server_allowed_ips', models.CharField(max_length=255)),
                ('client_ip', models.CharField(max_length=255)),
            ],
        ),
    ]
