# Generated by Django 2.2.4 on 2019-08-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerconfig',
            name='server_dns',
            field=models.CharField(default='10.10.10.1', max_length=255),
            preserve_default=False,
        ),
    ]
